# Generated by Django 4.1.7 on 2023-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
